title: Carlos Llanquinao
logo: /assets/img/profile.png
description: Aquí podras encontrar mis proyectos y experiencias, si tienes alguna consulta, no dudes en hacermela saber!
show_downloads: false 
# google_analytics:
theme: jekyll-theme-minimal
