title: Carlos Llanquinao
logo: /assets/img/profile.png
description: Enlace a mi trabajo en itch.io https://kenkii.itch.io Enlace a mi trabajo en Google Play https://play.google.com/store/apps/developer?id=Insert+media&hl=es_CL&gl=US
show_downloads: false 
# google_analytics:
theme: jekyll-theme-minimal
